name: c4_sweep_006
run:
  epochs: 10
  mask_ratio: 0.749
  seed: 20260626
stages:
  s1:
    active: &id001
    - progress: 0.0
      value: 0.0
    beta_sig: &id002
    - progress: 0.0
      value: 0.0
    freeze: &id003
    - progress: 0.0
      value: false
  s2:
    active: *id001
    beta_sig: *id002
    freeze: *id003
  s3:
    active: *id001
    beta_sig: *id002
    freeze: *id003
  s4:
    active:
    - progress: 0.0
      value: 1.0
    beta_sig:
    - progress: 0.0
      value: 41.719554
    freeze:
    - progress: 0.0
      value: false
augmentations:
  variant: tomo2
  crop_mode: resize
  global_views: 1
  local_views: 0
  random_rotate_deg: 0.0
  resize_jitter: null
  hflip_p: 0.5
  vflip_p: 0.5
  intensity_augment: true
  window:
    p_low: 0.01
    p_high: 0.99
    sample_size: 100000
  blur:
    kernel_size: 7
    sigma:
    - 0.1
    - 1.0
    p: 0.026229364484179386
  poisson:
    scale: 10000
    p: 0.0
  pixel_mask:
    ratio: 0.15
    p: 0.18791378949125825
  normalize:
    mean: 0.5
    std: 0.5
  equalize_p: 0.5587832242701521
